[theme]
primaryColor="#16697a"               # A deep teal for primary elements, offering a professional and calming effect
backgroundColor="#f1f1f1"            # A light grey background, which reduces eye strain and improves content readability
secondaryBackgroundColor="#ffffff"   # White for secondary backgrounds, providing a clean and modern feel
textColor="#111111"                  # Nearly black text color, enhancing contrast and readability on light backgrounds
font="sans serif"                    # Keeping sans serif for a modern and readable typography
